In [ ]:
pip install py-heideltime

Collecting py-heideltime
  Downloading py_heideltime-1.0.6-py3-none-any.whl.metadata (4.1 kB)
Collecting emoji==2.0.0 (from py-heideltime)
  Downloading emoji-2.0.0.tar.gz (197 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.3/197.3 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Downloading py_heideltime-1.0.6-py3-none-any.whl (72.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 MB 10.1 MB/s eta 0:00:00
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-2.0.0-py3-none-any.whl size=193007 sha256=dba7dbb0bf1f13429134263481e75bd7737cff501b00003b9bfae35728415667
  Stored in directory: /root/.cache/pip/wheels/8a/1b/ea/6710663acc2eda6eae91d6e18470da1874b004bd3a84fcafdb
Successfully built emoji
Installing collected packages: emoji, py-heideltime
Successfully installed emoji-2.0.0 py-heideltime-1.0.6

In [ ]:
!pip install gdown
!gdown --id 1jU264txlUGx4n0lWhb4VP41qBbPk-u_N
print("File downloaded successfully!")

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.24.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.1.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)
/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1jU264txlUGx4n0lWhb4VP41qBbPk-u_N
From (redirected): https://drive.google.com/uc?id=1jU264txlUGx4n0lWhb4VP41qBbPk-u_N&confirm=t&uuid=4d193a30-5000-4e34-afe1-95c6b8270595
To: /content/Processed_complete_dataset.json
100% 252M/252M [00:03<00:00, 66.6MB/s]
File downloaded successfully!

In [ ]:

import json
import pandas as pd
df = pd.read_json('Processed_complete_dataset.json')
df.head()

,claim,quantemp_evidences,label,Category,our_evidences,taxonomy,reranked_our_evidences
0,"""The non-partisan Congressional Budget Office ...",[{'questions': 'did the congressional budget o...,Conflicting,test,[{'question': 'Who concluded ObamaCare will co...,Statistical,[{'questions': 'Who concluded ObamaCare will c...
1,"""More than 50 percent of immigrants from (El S...",[{'questions': 'do more than 50 percent of imm...,True,test,[{'question': 'Which country has over 50 perce...,Statistical,[{'questions': 'Which country has over 50 perc...
2,UK government banned Covid vaccine for childre...,[{'questions': 'has the uk government banned t...,False,test,[{'question': 'Which government banned Covid v...,Temporal,[{'questions': 'Which government banned Covid ...
3,"""[In 2014-2015] coverage for the rotavirus vac...",[{'questions': 'did the coverage for the rotav...,False,test,[{'question': 'Which vaccine had 91.5% coverag...,Statistical,[{'questions': 'Which vaccine had 91.5% covera...
4,"In September 2021, the U.K. government announc...",[{'questions': 'is the u.k. government plannin...,True,test,[{'question': 'Which government announced its ...,Temporal,[{'questions': 'Which government announced its...

In [ ]:
temp = df[df["taxonomy"] == "Temporal"]
snippetss = []

for index, claim in enumerate(temp.our_evidences):
    for i, evidence in enumerate(claim):
      for j, snippets in enumerate(evidence['search_results']):
          snippet = snippets["snippet"]
          snippetss.append([index,i, j, snippet])
import pandas as pd
temp_df = pd.DataFrame(snippetss, columns=['claim_index', 'question_index', 'snippet_index', 'snippet'])
temp_df
temp_df = temp_df[temp_df.claim_index>3511][:1000]
print(temp_df.head())
print(temp_df.shape)
from py_heideltime import heideltime

def process_chunk(text_chunk):
    return heideltime(text_chunk)
from tqdm import tqdm
tqdm.pandas()

temp_df["result"] = temp_df['snippet'].progress_apply(process_chunk)

        claim_index  question_index  snippet_index  \
103729         3512               0              0
103730         3512               0              1
103731         3512               0              2
103732         3512               0              3
103733         3512               0              4

                                                  snippet
103729  May 22, 2021 ... Scam Alert People are receivi...
103730  May 22, 2021 ... People are receiving #COVID19...
103731  May 22, 2021 ... ... 912250041117". A WhatsApp...
103732  ... call from the number '912250041117' and if...
103733  ... 912250041117” for vaccine feedback and upo...
(1000, 4)

100%|██████████| 1000/1000 [1:05:09<00:00,  3.91s/it]

In [ ]:
temp_df.to_csv("0_1000.csv")

In [ ]:
from py_heideltime import heideltime

text = "Estimates by the City of Cape Town found that 161,000 individuals, or 11.3% of the total workforce, were employed by the informal economy in 2015."
results = heideltime(text)
print(results)

[{'text': '2015', 'tid': 't1', 'type': 'DATE', 'value': '2015', 'span': [141, 145]}]

In [ ]:

temp = df[(df.taxonomy == 'Temporal') & (df.Category != 'test')]
temp.head()

,claim,quantemp_evidences,label,Category,our_evidences,taxonomy,reranked_our_evidences
2498,Violence video shows rival groups fighting at ...,[{'questions': 'is there a video showing rival...,False,train,[{'question': 'Which group is fighting at the ...,Temporal,[{'questions': 'Which group is fighting at the...
2506,The video shows G20 delegates having lunch wit...,[{'questions': 'is there a video showing g20 d...,False,train,[{'question': 'What video shows G20 delegates ...,Temporal,[{'questions': 'What video shows G20 delegates...
2510,Does This Video Show Moldova Residents Blockin...,[{'questions': 'is there a video showing moldo...,False,train,[{'question': 'Does This Video Show Moldova Re...,Temporal,[{'questions': 'Does This Video Show Moldova R...
2511,Photo shows Imran Khan supporter waving gun du...,[{'questions': 'is there a photo showing an im...,Half True/False,train,[{'question': 'Which Imran Khan supporter wavi...,Temporal,[{'questions': 'Which Imran Khan supporter wav...
2513,A patent for coronavirus was granted in 2018 t...,[{'questions': 'was a patent for coronavirus g...,False,train,[{'question': 'Which patent was granted to the...,Temporal,[{'questions': 'Which patent was granted to th...

In [ ]:
temp.shape

(3512, 7)

In [ ]:
snippetss = []

for index, claim in enumerate(temp.our_evidences):
    for i, evidence in enumerate(claim):
      for snippets in evidence['search_results']:
          snippet = snippets["snippet"]
          snippetss.append([index,i, snippet])

In [ ]:
import pandas as pd
df = pd.DataFrame(snippetss, columns=['claim_index', 'question_index', 'snippet'])
df

,claim_index,question_index,snippet
0,0,0,"Mar 30, 2023 ... But does this video show viol..."
1,0,0,"Oct 10, 2025 ... Senegal and DR Congo will fig..."
2,0,0,"However, the premature eliminations of TP Maze..."
3,0,0,"Jul 1, 2025 ... Find out everything you need t..."
4,0,0,"Jan 2, 2024 ... ... Cup of Nations with a win ..."
...,...,...,...
103950,3511,2,Technology and Privacy · Trade Policy. Blog. M...
103951,3511,2,"Aug 5, 2025 ... You look at what's called the ..."
103952,3511,2,"Nov 2, 2022 ... ... can dump ballots. ... But ..."
103953,3511,2,"Aug 3, 2025 ... ... would undermine voting ......"
103954,3511,2,Voters who request a mail ballot and do not co...

In [ ]:
fr = 74000
to = 75000

In [ ]:
df = df[fr:to]

In [ ]:
def process_chunk(text_chunk):
    return heideltime(text_chunk)

In [ ]:
df.shape

(1000, 3)

In [ ]:
from tqdm import tqdm
tqdm.pandas()
df["result"] = df['snippet'].progress_apply(process_chunk)

100%|██████████| 1000/1000 [1:29:34<00:00,  5.37s/it]
/tmp/ipython-input-1699155112.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["result"] = df['snippet'].progress_apply(process_chunk)

In [ ]:
df

,claim_index,question_index,snippet,result
74000,2504,0,"... presidential election, equipment manufactu...","[{'text': '2020', 'tid': 't1', 'type': 'DATE',..."
74001,2504,0,"Sep 29, 2025 ... For instance, Lindell claims ...","[{'text': 'Sep 29, 2025', 'tid': 't2', 'type':..."
74002,2504,1,"Oct 22, 2022 ... ... election fraud in Brazil....","[{'text': 'Oct 22, 2022', 'tid': 't2', 'type':..."
74003,2504,1,"Mar 22, 2025 ... ... voting machines and syste...","[{'text': 'Mar 22, 2025', 'tid': 't2', 'type':..."
74004,2504,1,shows that Smartmatic has not designed any of ...,"[{'text': '2020', 'tid': 't1', 'type': 'DATE',..."
...,...,...,...,...
74995,2537,1,"According to NPR, ""By definition, 'insurrectio...",[]
74996,2537,1,"Jan 11, 2021 ... By now, we're all familiar wi...","[{'text': 'Jan 11, 2021', 'tid': 't2', 'type':..."
74997,2537,1,"Jan 13, 2009 ... Insurgency is the organized u...","[{'text': 'Jan 13, 2009', 'tid': 't2', 'type':..."
74998,2537,1,"Apr 14, 2022 ... ... country expressing concer...","[{'text': 'Apr 14, 2022', 'tid': 't2', 'type':..."
74999,2537,1,"Jun 7, 2013 ... The U.S. Capitol was stormed o...","[{'text': 'Jun 7, 2013', 'tid': 't2', 'type': ..."

In [ ]:
df.to_csv(f"{fr}_to_{to}.csv")